# Generated by Django 3.2.7 on 2021-09-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conference',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='talk',
            options={'ordering': ['-id']},
        ),
        migrations.RenameField(
            model_name='talk',
            old_name='conference_id',
            new_name='conference',
        ),
        migrations.AlterField(
            model_name='person',
            name='email_id',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
